### PR TITLE
Resolve the confliction of log4j2 configuration between the agent and  the user's application.

### PR DESCRIPTION
**Pull request by Oseenix**
when the user's application use the log4j2, it would find the configuration file 'log4j2.xml' in the classpath. The agent jar is included in the classpath with the log4j2.xml file, so it may be found and use by the user's application.
So the solution can be simple: change the configuration file name in the agent jar.

### CODE REVIEW

**Comment by Oseenix** [comment]
change the configuration file name in the agent jar.

**Comment by jxd134** [comment]
Agree with it.
Maybe `easeagent.xml` is better.

**Comment by Oseenix** [comment]
The problem can't be reproduced in debug mode, but it is easy to be reproduced like this:
```
java  -javaagent:'path-to-agent'/easeagent-dep.jar=/path-to-agent-configuration/agent.properties -Deaseagent.server.port=9901 -Deaseagent.middleware.update=true -jar target/springboot0-1.0-SNAPSHOT.jar
```

**Comment by zhao-kun** [comment]
The PR isn't completely fulfilling the requirement of our Github workflow, Pls prune the useless commits from it and push it again

**Pull request closed without merging**
