### PR TITLE
[fix test] fix test failed error

### PR DESCRIPTION
**Pull request by jxd134**

### CODE REVIEW

**Review by Oseenix — COMMENTED** [review]
these unit test cases should not fail, if they fail, it means that the classes transform have some problems.
for example, the "kkk" value used in the test code of `NewInstanceMethodTransformTest` can be replace by another string, like "ddd" except QUX.

Can you provide more details of the test failures?  steps? jdk version? os environment?

**Comment by jxd134** [comment]
Test Result

JDK version: adopt-openj9-1.8.0_282
Platform: Win10

**Comment by Oseenix** [comment]
> Test Result
> 
> JDK version: adopt-openj9-1.8.0_282 Platform: Win10
> 
> For example:
> 
> ```java
>     public static class FooInterceptor implements Interceptor {
>         @Override
>         public void before(MethodInfo methodInfo, Context context) {
>             Object [] args = methodInfo.getArgs();
>             args[0] = QUX;
>             methodInfo.markChanged();
>         }
> 
>         @Override
>         public void after(MethodInfo methodInfo, Context context) {
>             methodInfo.setRetValue(methodInfo.getRetValue() + BAR);
>         }
> 
>         @Override
>         public int order() {
>             return Order.HIGHEST.getOrder();
>         }
>     }
> ```
> 
> When i call `Foo` class method, the return value should append `BAR`.
> 
> ```java
>        // StaticMethodTransformTest.testStaticAdviceTransformer method
>         Set<MethodTransformation> transformations = getMethodTransformations(globalIndex.incrementAndGet(),
>             FOO_STATIC, new FooProvider());
> 
>         ClassFileTransformer classFileTransformer = builder
>             .type(ElementMatchers.is(Foo.class), ElementMatchers.is(classLoader))
>             .transform(PluginLoader.compound(false, transformations))
>             .installOnByteBuddyAgent();
> 
>         try {
>             Class<?> type = classLoader.loadClass(Foo.class.getName());
>             // check
>             assertThat(type.getDeclaredMethod(FOO_STATIC, String.class)
>                     .invoke(null, "kkk"),
>                 is(QUX + BAR)); 
>         } finally {
>             assertThat(ByteBuddyAgent.getInstrumentation().removeTransformer(classFileTransformer), is(true));
>         }
> ```
> 
> When i call `Foo.fooStatic` method with value `kkk`., it should return `kkkbar` but not `QUX + BAR`.

the `kkk` has been replace by `QUX` in the before method.

    public void before(MethodInfo methodInfo, Context context) {
            Object [] args = methodInfo.getArgs();
            args[0] = QUX;
            methodInfo.markChanged();
    }

I will test this case in OpenJ9VM

**Comment by jxd134** [comment]
@Oseenix 
Wait for you test result.

**Comment by Oseenix** [comment]
> @Oseenix
> Wait for you test result.

Test passed on MACOS + openJ9 - 292, still need to verify on Window 10, thanks for @jxd134 's support:

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210421_909 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)
----------------------
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/Henry/.sdkman/candidates/maven/current
Java version: 1.8.0_292, vendor: AdoptOpenJDK, runtime: /Users/Henry/.sdkman/candidates/java/8.0.292.j9-adpt/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by haoel** [comment]
@jxd134  once the #159 merged, you can add the `windows-latest` into the GitHub action - `build.strategy.matrix.os`

**Comment by Oseenix** [comment]
> > @Oseenix
> > Wait for you test result.
> 
> Test passed on MACOS + openJ9 - 292, still need to verify on Window 10, thanks for @jxd134 's support:
> 
> ```
> java -version
> openjdk version "1.8.0_292"
> OpenJDK Runtime Environment (build 1.8.0_292-b10)
> Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210421_909 (JIT enabled, AOT enabled)
> OpenJ9   - b4cc246d9
> OMR      - 162e6f729
> JCL      - 2a5e268814 based on jdk8u292-b10)
> ```
> 
>  ```
> Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
> Maven home: /Users/Henry/.sdkman/candidates/maven/current
> Java version: 1.8.0_292, vendor: AdoptOpenJDK, runtime: /Users/Henry/.sdkman/candidates/java/8.0.292.j9-adpt/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "mac os x", version: "10.16", arch: "x86_64", family: "Mac"
> ```

@jxd134  Thank you for you PR and Issue #157❤️ , which exposes several compile and testing problems on windows platform. These problems are solved with commit #163, and the Build/Test process on GitHub Action will run on both Ubuntu-lastest,and Windows-lastest covering OpenJDK-hs-8/11/16 and OpenJDK-j9-8/11/16 now.

**Pull request closed without merging**
